allowBuilds:
  '@clerk/shared': true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@clerk/shared'
  - sharp
  - unrs-resolver
overrides:
  minimatch: '>=10.2.3'
  ajv: '>=8.18.0'
  flatted: '>=3.4.2'
  picomatch@<2.3.2: 2.3.2
  picomatch@>=4.0.0 <4.0.4: 4.0.4
  yaml: '>=2.8.3'
  brace-expansion: '>=5.0.5'
  follow-redirects: '>=1.16.0'
  postcss: 8.5.14
