"""add release_dates jsonb

Revision ID: 030af05b935f
Revises: 5bc6f1d9a564
Create Date: 2026-02-05 15:46:10.787920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '030af05b935f'
down_revision: Union[str, None] = '5bc6f1d9a564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('release_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('idx_movie_letterboxd_rating', table_name='movies')
    op.drop_index('idx_movie_popularity', table_name='movies')
    op.drop_index('idx_movie_vectorbox_score', table_name='movies')
    op.drop_index('idx_movie_vote_count', table_name='movies')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'release_dates')
    op.create_index('idx_movie_vote_count', 'movies', ['vote_count'], unique=False)
    op.create_index('idx_movie_vectorbox_score', 'movies', ['vectorbox_score'], unique=False)
    op.create_index('idx_movie_popularity', 'movies', ['popularity'], unique=False)
    op.create_index('idx_movie_letterboxd_rating', 'movies', ['letterboxd_rating'], unique=False)
    # ### end Alembic commands ###
