"""check_letterboxd_rating

Revision ID: 0bf92d290e01
Revises: 7c6942b7aa84
Create Date: 2025-12-31 18:03:09.792720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bf92d290e01'
down_revision: Union[str, None] = '7c6942b7aa84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
