"""v1_init_schema

Revision ID: 5daf98544a53
Revises: 
Create Date: 2026-01-07 21:24:24.285254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5daf98544a53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('backdrop_path', sa.String(length=255), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('letterboxd_uri', sa.String(length=500), nullable=True),
    sa.Column('letterboxd_rating', sa.Float(), nullable=True),
    sa.Column('directors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('cast', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('imdb_rating', sa.Float(), nullable=True),
    sa.Column('metacritic_rating', sa.Integer(), nullable=True),
    sa.Column('rotten_tomatoes_rating', sa.Integer(), nullable=True),
    sa.Column('vectorbox_score', sa.Float(), nullable=True),
    sa.Column('title_es', sa.String(length=500), nullable=True),
    sa.Column('overview_es', sa.Text(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb_id')
    )
    op.create_index('idx_movie_tmdb', 'movies', ['tmdb_id'], unique=False)
    op.create_index('idx_movie_year_genre', 'movies', ['year', 'genres'], unique=False)
    op.create_index(op.f('ix_movies_collection_id'), 'movies', ['collection_id'], unique=False)
    op.create_index(op.f('ix_movies_id'), 'movies', ['id'], unique=False)
    op.create_index(op.f('ix_movies_tmdb_id'), 'movies', ['tmdb_id'], unique=True)
    op.create_index(op.f('ix_movies_year'), 'movies', ['year'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('secret_token', sa.UUID(), nullable=True),
    sa.Column('letterboxd_username', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_letterboxd_username'), 'users', ['letterboxd_username'], unique=False)
    op.create_index(op.f('ix_users_secret_token'), 'users', ['secret_token'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('movie_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('providers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_movie_country', 'movie_availability', ['movie_id', 'country_code'], unique=True)
    op.create_index(op.f('ix_movie_availability_id'), 'movie_availability', ['id'], unique=False)
    op.create_table('streaming_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_provider', 'streaming_providers', ['user_id', 'provider_id'], unique=True)
    op.create_index(op.f('ix_streaming_providers_id'), 'streaming_providers', ['id'], unique=False)
    op.create_table('user_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('cluster_label', sa.String(length=100), nullable=True),
    sa.Column('movie_count', sa.Integer(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('dominant_genres', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('sample_movie_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_cluster', 'user_clusters', ['user_id', 'cluster_id'], unique=True)
    op.create_index(op.f('ix_user_clusters_id'), 'user_clusters', ['id'], unique=False)
    op.create_table('user_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('is_watchlist', sa.Boolean(), nullable=True),
    sa.Column('is_liked', sa.Boolean(), nullable=True),
    sa.Column('is_watched', sa.Boolean(), nullable=True),
    sa.Column('watched_date', sa.DateTime(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_movie', 'user_ratings', ['user_id', 'movie_id'], unique=True)
    op.create_index(op.f('ix_user_ratings_id'), 'user_ratings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_ratings_id'), table_name='user_ratings')
    op.drop_index('idx_user_movie', table_name='user_ratings')
    op.drop_table('user_ratings')
    op.drop_index(op.f('ix_user_clusters_id'), table_name='user_clusters')
    op.drop_index('idx_user_cluster', table_name='user_clusters')
    op.drop_table('user_clusters')
    op.drop_index(op.f('ix_streaming_providers_id'), table_name='streaming_providers')
    op.drop_index('idx_user_provider', table_name='streaming_providers')
    op.drop_table('streaming_providers')
    op.drop_index(op.f('ix_movie_availability_id'), table_name='movie_availability')
    op.drop_index('idx_movie_country', table_name='movie_availability')
    op.drop_table('movie_availability')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_secret_token'), table_name='users')
    op.drop_index(op.f('ix_users_letterboxd_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_movies_year'), table_name='movies')
    op.drop_index(op.f('ix_movies_tmdb_id'), table_name='movies')
    op.drop_index(op.f('ix_movies_id'), table_name='movies')
    op.drop_index(op.f('ix_movies_collection_id'), table_name='movies')
    op.drop_index('idx_movie_year_genre', table_name='movies')
    op.drop_index('idx_movie_tmdb', table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###
