"""add cast and director columns

Revision ID: 7c6942b7aa84
Revises: c8de0d0bce01
Create Date: 2025-12-31 16:38:53.515816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c6942b7aa84'
down_revision: Union[str, None] = 'c8de0d0bce01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('directors', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('movies', sa.Column('cast', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'cast')
    op.drop_column('movies', 'directors')
    # ### end Alembic commands ###
