"""add_movie_metadata

Revision ID: b1d45f76893c
Revises: 
Create Date: 2025-11-26 18:28:29.540218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1d45f76893c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('movies', sa.Column('vote_count', sa.Integer(), nullable=True))
    # op.add_column('movies', sa.Column('popularity', sa.Float(), nullable=True))
    # op.add_column('movies', sa.Column('original_language', sa.String(length=10), nullable=True))
    # op.add_column('movies', sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'keywords')
    op.drop_column('movies', 'original_language')
    op.drop_column('movies', 'vote_count')
    # ### end Alembic commands ###
